### PR TITLE
Implement Search API

### PR DESCRIPTION
**Pull request by sjhan-moloco**
- Use `flex-search` module to implement full-text search over product titles
  - Use pre-built static search index uploaded to GCS

### CODE REVIEW

**Review by dexterastin — APPROVED** [review]
LGTM

**Comment by dexterastin** [comment]
Please click handler on search icon and back icon in the next PR.
image

**Comment by dexterastin** [comment]
nit: How about adding logic for debounce on search form?

**Comment by sjhan-moloco** [comment]
> nit: How about adding logic for debounce on search form?

I think we don't need to debounce because the search form is not being auto-submitted (you need to press the enter key to do search.)

**Pull request merged**
